"""No em dash anywhere in tracked text files.

The project style forbids U+2014 in every tracked text file. This test
fails loudly if one appears, so the violation is caught here instead
of slipping into docs or code comments.
"""
import pathlib
import subprocess

REPO = pathlib.Path(__file__).resolve().parents[1]
EM_DASH = "\u2014"

# Binary or generated by design: skip these paths when scanning.
SKIP_SUFFIXES = (".pyc", ".png", ".jpg", ".jpeg", ".gif", ".ico",
                 ".woff", ".woff2", ".ttf", ".eot", ".pdf")
SKIP_DIRS = {".git", "__pycache__", ".venv", "venv", "node_modules"}


def _tracked_files():
    out = subprocess.check_output(["git", "ls-files", "-z"],
                                  cwd=REPO)
    return [p for p in out.decode("utf-8").split("\0") if p]


def test_no_em_dash_in_tracked_files():
    offenders = []
    for rel in _tracked_files():
        if rel.endswith(SKIP_SUFFIXES):
            continue
        if any(part in SKIP_DIRS for part in rel.split("/")):
            continue
        path = REPO / rel
        if not path.is_file():
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except (UnicodeDecodeError, OSError):
            continue
        for i, line in enumerate(text.splitlines(), 1):
            if EM_DASH in line:
                offenders.append("%s:%d" % (rel, i))
    assert offenders == [], \
        "em dash found in tracked files: %s" % ", ".join(offenders)
